export const ADAPTIVE_CARD_QUOTES = [
  "Fixed a bug that I created",
  "Added some magic",
  "It works on my machine",
  "Oops",
  "I have no idea what I’m doing",
  "This is fine",
  "Trust me, I’m an engineer",
  "YOLO",
  "I’m sorry, future me",
  "This is not a bug, it’s a feature",
  "I can’t believe this works",
  "Don’t ask me why",
  "I did a thing",
  "Here be dragons",
  "Hold my beer",
  "Let’s hope this works",
  "I’m not a smart man",
  "May the force be with you",
  "That’s what she said",
  "It’s not a bug, it’s an undocumented feature",
  "I have no clue what I just did",
  "This code sucks, but it works",
  "I need a vacation",
  "I'm too lazy to write a proper message",
  "I swear this is the last one",
  "I should have used a linter",
  "I hate this project",
  "I'm sorry for what I'm about to do",
  "It was like that when I got here",
  "Please don't fire me",
  "This is why we can't have nice things",
  "I'm not drunk, I swear",
  "Just testing something, ignore this",
  "Shh, don't tell anyone",
  "Coding is hard",
  "I should have slept more",
  "I hope nobody sees this",
  "This is the best I can do",
  "I'm sorry, Dave. I'm afraid I can't do that",
  "Houston, we have a problem",
  "I'm not a wizard, I just googled it",
  "This is the last time I code sober",
  "I wish I knew what I was doing",
  "I'm sorry, mom",
  "I'm a genius",
  "This is Sparta",
  "I'm feeling lucky",
  "I'm Batman",
  "There's no place like home",
  "To be or not to be",
  "The cake is a lie",
  "Winter is coming",
  "May the odds be ever in your favor",
  "Live long and prosper",
  "Hakuna matata",
  "You shall not pass",
  "Do or do not, there is no try",
  "One does not simply code without bugs",
  "The force is strong with this one",
  "These are not the droids you are looking for",
  "Luke, I am your father",
  "Houston, we have a solution",
  "E.T. phone home",
  "I'll be back",
  "Hasta la vista, baby",
  "Say hello to my little friend",
  "You're a wizard, Harry",
  "You're killing me, Smalls",
  "Frankly, my dear, I don't give a damn",
  "I'm the king of the world",
];
